name: task
description: A new Flutter project.

publish_to:

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  google_fonts: 3.0.1
  flutter_staggered_grid_view: ^0.4.0
  cached_network_image: ^3.2.0
  nb_utils: 4.4.10
  flutter_bloc: ^7.0.0
  equatable: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/Greoup 3.png
    - assets/images/user_2.png
    - assets/images/user_3.png
    - assets/images/user_4.png
    - assets/images/user_5.png
    - assets/images/oranos.png